<?php

use App\Enums\Feature\FeatureStatus;
use App\Enums\Feature\FeatureType;
use Illuminate\Support\Facades\Route;

Route::get('/tasks', function () {
    return [
        [
            'id' => 1,
            'name' => 'User authentication with OAuth2',
            'description' => 'Implement OAuth2 login flow supporting Google and GitHub providers.',
            'status' => FeatureStatus::Planned->value,
            'type' => FeatureType::Feature->value,
            'effort_in_days' => 5,
            'priority' => 1,
            'cost' => 4500.00,
            'target_delivery_date' => '2026-05-01',
        ],
        [
            'id' => 2,
            'name' => 'Dashboard analytics overview',
            'description' => 'Add a summary widget showing key metrics on the main dashboard.',
            'status' => FeatureStatus::InProgress->value,
            'type' => FeatureType::Feature->value,
            'effort_in_days' => 3,
            'priority' => 2,
            'cost' => 2800.00,
            'target_delivery_date' => '2026-04-15',
        ],
        [
            'id' => 3,
            'name' => 'Export table data to CSV',
            'description' => 'Allow users to export any table in the application to a CSV file.',
            'status' => FeatureStatus::Proposed->value,
            'type' => FeatureType::Feature->value,
            'effort_in_days' => 2,
            'priority' => 4,
            'cost' => 1200.00,
            'target_delivery_date' => '2026-06-01',
        ],
        [
            'id' => 4,
            'name' => 'Fix pagination on mobile',
            'description' => 'Pagination controls overflow on small screens, buttons are not tappable.',
            'status' => FeatureStatus::InProgress->value,
            'type' => FeatureType::Bug->value,
            'effort_in_days' => 1,
            'priority' => 1,
            'cost' => 600.00,
            'target_delivery_date' => '2026-04-10',
        ],
        [
            'id' => 5,
            'name' => 'Email notification system',
            'description' => 'Send transactional emails when key events occur, such as status changes.',
            'status' => FeatureStatus::Planned->value,
            'type' => FeatureType::Feature->value,
            'effort_in_days' => 4,
            'priority' => 3,
            'cost' => 3200.00,
            'target_delivery_date' => '2026-05-20',
        ],
        [
            'id' => 6,
            'name' => 'Role-based access control',
            'description' => 'Restrict access to resources based on user roles (admin, editor, viewer).',
            'status' => FeatureStatus::Proposed->value,
            'type' => FeatureType::Feature->value,
            'effort_in_days' => 7,
            'priority' => 2,
            'cost' => 6000.00,
            'target_delivery_date' => '2026-07-01',
        ],
        [
            'id' => 7,
            'name' => 'Session timeout after inactivity',
            'description' => 'Automatically log out users after 30 minutes of inactivity.',
            'status' => FeatureStatus::Completed->value,
            'type' => FeatureType::Feature->value,
            'effort_in_days' => 1,
            'priority' => 3,
            'cost' => 800.00,
            'target_delivery_date' => '2026-03-15',
        ],
        [
            'id' => 8,
            'name' => 'Broken image upload on Safari',
            'description' => 'File input does not trigger on Safari 17, preventing image uploads.',
            'status' => FeatureStatus::InProgress->value,
            'type' => FeatureType::Bug->value,
            'effort_in_days' => 2,
            'priority' => 1,
            'cost' => 1000.00,
            'target_delivery_date' => '2026-04-08',
        ],
        [
            'id' => 9,
            'name' => 'Dark mode support',
            'description' => 'Add a dark mode toggle that persists the user preference across sessions.',
            'status' => FeatureStatus::Proposed->value,
            'type' => FeatureType::Feature->value,
            'effort_in_days' => 3,
            'priority' => 5,
            'cost' => 2200.00,
            'target_delivery_date' => '2026-06-15',
        ],
        [
            'id' => 10,
            'name' => 'API rate limiting',
            'description' => 'Throttle API requests per user to prevent abuse and ensure fair usage.',
            'status' => FeatureStatus::Planned->value,
            'type' => FeatureType::Feature->value,
            'effort_in_days' => 2,
            'priority' => 3,
            'cost' => 1500.00,
            'target_delivery_date' => '2026-05-10',
        ],
    ];
})->name('api.tasks');
